"""
A module which handles uncertainty propagation from instrumentation to points.

This module is generally called in :py:class:georefencer, but can be used as a stand-alone module to estimate the impact of various intrument parameters on output data uncertainties.

:py:class:createJacobians uses :py:module:SymPy to generate and write out the partial derivatives required to perform variance-covariance propagation through the LiDAR georefereincing equation. This needs to be run once for every instrument configuration, results are stored in a configuration file which is referred to in the georeferencing process.

:py:class:computeUncertainties uses the configuration file generated by :py:class:createJacobians to produce X, Y and Up uncertainties for each LiDAR point at processing time. These are stored as extra dimensions in the desired output file.

#just getting started

Adam Steer
2017
"""
#collect dependencies
import numpy as np
import sys
